# Generated by Django 3.2.15 on 2022-08-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='clinic.userprofile'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
