# Generated by Django 3.2.15 on 2022-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20220829_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
