# Generated by Django 3.2.15 on 2022-08-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reception', to='clinic.reception')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reception', to='clinic.userprofile')),
            ],
        ),
    ]
