# Generated by Django 3.2.15 on 2022-08-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20220830_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
