# Generated by Django 3.2.15 on 2022-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_rename_result_visit_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit',
        ),
        migrations.AlterField(
            model_name='visit',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
