# Generated by Django 3.2.15 on 2022-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_auto_20220831_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
