# Generated by Django 3.2.15 on 2022-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_reception_in_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
