# Generated by Django 5.0.2 on 2024-02-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_auto_20231014_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='patient',
        ),
        migrations.AlterField(
            model_name='reception',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='clinic.userprofile'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='in_use',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='ReserveReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='clinic.userprofile')),
                ('reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='clinic.reception')),
            ],
        ),
    ]
